apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bss-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brmorris/bss-operator.git
    targetRevision: HEAD
    path: config/default
  destination:
    server: https://kubernetes.default.svc
    namespace: bss-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
