apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bss-clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brmorris/bss-operator.git
    targetRevision: HEAD
    path: config/samples
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
